version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_DB:       price_guesser
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      DB_HOST:     postgres
      DB_PORT:     5432
      DB_NAME:     price_guesser
      DB_USER:     postgres
      DB_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_net

  parser:
    build:
      context: ./parser
    container_name: parser
    restart: "no"
    environment:
      DB_HOST:     172.19.0.2
      DB_PORT:     5432
      DB_NAME:     price_guesser
      DB_USER:     postgres
      DB_PASSWORD: ${DB_PASSWORD:-password}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_net
    # Контейнер просто ждёт — запускаешь вручную через Portainer
    command: tail -f /dev/null

volumes:
  pg_data:

networks:
  app_net:
    driver: bridge
